stages:
  - build
  - deploy

image: busybox

build:
  stage: build
  script:
    - echo "Creation d'un timestamp pour eviter le cache..."
    - timestamp=$(date +%s)
    - echo "Copie du moteur dans les dossiers des jeux..."
    - cp ./www/moteurldvelh.js ./www/jeux/1_jeu_exemple/data/
    - cp ./www/moteurldvelh.js ./www/jeux/cyberpunk/data/
    - echo "Modification des chemins dans les index.htm..."
    - sed -i "s,../../moteurldvelh.js,data/moteurldvelh.js?$timestamp," ./www/jeux/1_jeu_exemple/index.htm
    - sed -i "s,../../moteurldvelh.js,data/moteurldvelh.js?$timestamp," ./www/jeux/cyberpunk/index.htm
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public

e2e tests:
stage: e2e
  image: mcr.microsoft.com/playwright:v1.36.0-jammy
  parallel: 7
  script:
    - npm run start
    - npm ci
    - npx playwright test

pages: #GitLab détecte ce mot "page" et fait l'upload avec un job pages:deploy derrière, cf https://stackoverflow.com/questions/53953919/
  dependencies:
    - build
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public