stages:
  - build
  - deploy

job1:
  image: busybox
  stage: build
  script:
    - echo "Creation d'un timestamp pour eviter le cache..."
    - timestamp=$(date +%s)
    - echo "Copie du moteur dans les dossiers des jeux..."
    - cp moteurldvelh.js ./jeux/1_jeu_exemple/data/
    - cp moteurldvelh.js ./jeux/cyberpunk/data/
    - echo "Modification des chemins dans les index.htm..."
    - sed -i "s,../../moteurldvelh.js,data/moteurldvelh.js?$timestamp," ./jeux/1_jeu_exemple/index.htm
    - sed -i "s,../../moteurldvelh.js,data/moteurldvelh.js?$timestamp," ./jeux/cyberpunk/index.htm
    
pages:
image: busybox
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
