stages:
  - build
  - deploy

image: busybox

reorganise-html-js:
  stage: build
  script:
    - echo "coucou"

image: busybox

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    
