name: my-pretty-test-and-deploy-pipeline
run-name: Testing the sample game with Playwright then deploy to GitHub pages
# Will be launched in case of...
on:
  # ...a push.
  push:
    branches: ["tryingGhActions"]
    # ...a manual from the Actions tab
    workflow_dispatch:
jobs:
  testing-cyoa-engine-using-playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: starting node server
      run: npm run start&
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  the-pretty-deployment:
    needs: testing-cyoa-engine-using-playwright
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      # This "github-pages" environment is created automatically by GitHub
      # check the deployment rules here https://github.com/marl1/cyoajsengine/settings/environments
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
      # Git checkout on the tryingGhActions branch
      - name: Checkout
        uses: actions/checkout@v4        
        with:
          ref: tryingGhActions
      # Enable Pages and extract various metadata about a site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only the content of this folder, will be on https://marl1.github.io/cyoajsengine/
          path: './www'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
